[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_NETLIFY_IDENTITY_URL = "https://your-site-name.netlify.app/.netlify/identity"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "node_modules/@netlify/functions/**/*",
    "node_modules/next/**/*",
    "node_modules/react/**/*",
    "node_modules/react-dom/**/*",
    "node_modules/netlify-identity-widget/**/*"
  ]
  node_bundler = "esbuild" 